---
- hosts: all
  sudo: true
  tasks:
    - name: add gpg docker key
      apt_key: keyserver="hkp://p80.pool.sks-keyservers.net:80" id=58118E89F3A912897C070ADBF76221572C52609D
    - name: add docker repo entry to apt
      copy: content="deb https://apt.dockerproject.org/repo ubuntu-trusty main" dest=/etc/apt/sources.list.d/docker.list
    - name: apt update and cache
      apt: update_cache=yes
    - shell: "uname -r"
      register: uname
    - name: install required packages
      apt: name={{ item }} state=latest
      with_items:
        - "linux-image-extra-{{ uname.stdout }}"
        - "docker-engine"
    - name: set docker options
      lineinfile: dest=/etc/default/docker regexp="^#DOCKER_OPTS" line='DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -D -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"'
    - name: add docker group
      user: name=vagrant group=docker append=yes
    - name: restart docker
      service: name=docker state=restarted
